package com.matjazmav.googlekickstartme.util;

import java.util.*;

public class CountryFlagImageMapper {
    public static final Map<String, String> MAP = new TreeMap<>(String.CASE_INSENSITIVE_ORDER){{
        put("Afghanistan", f("AF"));
        put("Albania", f("AL"));
        put("Algeria", f("DZ"));
        put("American Samoa", f("AS"));
        put("Andorra", f("AD"));
        put("Angola", f("AO"));
        put("Anguilla", f("AI"));
        put("Antarctica", f("AQ"));
        put("Antigua and Barbuda", f("AG"));
        put("Argentina", f("AR"));
        put("Armenia", f("AM"));
        put("Aruba", f("AW"));
        put("Australia", f("AU"));
        put("Austria", f("AT"));
        put("Azerbaijan", f("AZ"));
        put("Bahamas", f("BS"));
        put("Bahrain", f("BH"));
        put("Bangladesh", f("BD"));
        put("Barbados", f("BB"));
        put("Belarus", f("BY"));
        put("Belgium", f("BE"));
        put("Belize", f("BZ"));
        put("Benin", f("BJ"));
        put("Bermuda", f("BM"));
        put("Bhutan", f("BT"));
        put("Bolivia", f("BO"));
        put("Bosnia and Herzegovina", f("BA"));
        put("Botswana", f("BW"));
        put("Brazil", f("BR"));
        put("British Indian Ocean Territory", f("IO"));
        put("British Virgin Islands", f("VG"));
        put("Brunei", f("BN"));
        put("Bulgaria", f("BG"));
        put("Burkina Faso", f("BF"));
        put("Burundi", f("BI"));
        put("Cambodia", f("KH"));
        put("Cameroon", f("CM"));
        put("Canada", f("CA"));
        put("Cape Verde", f("CV"));
        put("Cayman Islands", f("KY"));
        put("Central African Republic", f("CF"));
        put("Chad", f("TD"));
        put("Chile", f("CL"));
        put("China", f("CN"));
        put("Christmas Island", f("CX"));
        put("Cocos Islands", f("CC"));
        put("Colombia", f("CO"));
        put("Comoros", f("KM"));
        put("Cook Islands", f("CK"));
        put("Costa Rica", f("CR"));
        put("Croatia", f("HR"));
        put("Cuba", f("CU"));
        put("Curacao", f("CW"));
        put("Cyprus", f("CY"));
        put("Czech Republic", f("CZ"));
        put("Democratic Republic of the Congo", f("CD"));
        put("Denmark", f("DK"));
        put("Djibouti", f("DJ"));
        put("Dominica", f("DM"));
        put("Dominican Republic", f("DO"));
        put("East Timor", f("TL"));
        put("Ecuador", f("EC"));
        put("Egypt", f("EG"));
        put("El Salvador", f("SV"));
        put("Equatorial Guinea", f("GQ"));
        put("Eritrea", f("ER"));
        put("Estonia", f("EE"));
        put("Ethiopia", f("ET"));
        put("Falkland Islands", f("FK"));
        put("Faroe Islands", f("FO"));
        put("Fiji", f("FJ"));
        put("Finland", f("FI"));
        put("France", f("FR"));
        put("French Polynesia", f("PF"));
        put("Gabon", f("GA"));
        put("Gambia", f("GM"));
        put("Georgia", f("GE"));
        put("Germany", f("DE"));
        put("Ghana", f("GH"));
        put("Gibraltar", f("GI"));
        put("Greece", f("GR"));
        put("Greenland", f("GL"));
        put("Grenada", f("GD"));
        put("Guam", f("GU"));
        put("Guatemala", f("GT"));
        put("Guernsey", f("GG"));
        put("Guinea", f("GN"));
        put("Guinea Bissau", f("GW"));
        put("Guyana", f("GY"));
        put("Haiti", f("HT"));
        put("Honduras", f("HN"));
        put("Hong Kong", f("HK"));
        put("Hungary", f("HU"));
        put("Iceland", f("IS"));
        put("India", f("IN"));
        put("Indonesia", f("ID"));
        put("Iran", f("IR"));
        put("Iraq", f("IQ"));
        put("Ireland", f("IE"));
        put("Isle of Man", f("IM"));
        put("Israel", f("IL"));
        put("Italy", f("IT"));
        put("Ivory Coast", f("CI"));
        put("Jamaica", f("JM"));
        put("Japan", f("JP"));
        put("Jersey", f("JE"));
        put("Jordan", f("JO"));
        put("Kazakhstan", f("KZ"));
        put("Kenya", f("KE"));
        put("Kiribati", f("KI"));
        put("Kosovo", f("XK"));
        put("Kuwait", f("KW"));
        put("Kyrgyzstan", f("KG"));
        put("Laos", f("LA"));
        put("Latvia", f("LV"));
        put("Lebanon", f("LB"));
        put("Lesotho", f("LS"));
        put("Liberia", f("LR"));
        put("Libya", f("LY"));
        put("Liechtenstein", f("LI"));
        put("Lithuania", f("LT"));
        put("Luxembourg", f("LU"));
        put("Macau", f("MO"));
        put("Macedonia", f("MK"));
        put("Madagascar", f("MG"));
        put("Malawi", f("MW"));
        put("Malaysia", f("MY"));
        put("Maldives", f("MV"));
        put("Mali", f("ML"));
        put("Malta", f("MT"));
        put("Marshall Islands", f("MH"));
        put("Mauritania", f("MR"));
        put("Mauritius", f("MU"));
        put("Mayotte", f("YT"));
        put("Mexico", f("MX"));
        put("Micronesia", f("FM"));
        put("Moldova", f("MD"));
        put("Monaco", f("MC"));
        put("Mongolia", f("MN"));
        put("Montenegro", f("ME"));
        put("Montserrat", f("MS"));
        put("Morocco", f("MA"));
        put("Mozambique", f("MZ"));
        put("Myanmar", f("MM"));
        put("Namibia", f("NA"));
        put("Nauru", f("NR"));
        put("Nepal", f("NP"));
        put("Netherlands", f("NL"));
        put("Netherlands Antilles", f("AN"));
        put("New Caledonia", f("NC"));
        put("New Zealand", f("NZ"));
        put("Nicaragua", f("NI"));
        put("Niger", f("NE"));
        put("Nigeria", f("NG"));
        put("Niue", f("NU"));
        put("North Korea", f("KP"));
        put("Northern Mariana Islands", f("MP"));
        put("Norway", f("NO"));
        put("Oman", f("OM"));
        put("Pakistan", f("PK"));
        put("Palau", f("PW"));
        put("Palestine", f("PS"));
        put("Panama", f("PA"));
        put("Papua New Guinea", f("PG"));
        put("Paraguay", f("PY"));
        put("Peru", f("PE"));
        put("Philippines", f("PH"));
        put("Pitcairn", f("PN"));
        put("Poland", f("PL"));
        put("Portugal", f("PT"));
        put("Puerto Rico", f("PR"));
        put("Qatar", f("QA"));
        put("Republic of the Congo", f("CG"));
        put("Reunion", f("RE"));
        put("Romania", f("RO"));
        put("Russia", f("RU"));
        put("Rwanda", f("RW"));
        put("Saint Barthelemy", f("BL"));
        put("Saint Helena", f("SH"));
        put("Saint Kitts and Nevis", f("KN"));
        put("Saint Lucia", f("LC"));
        put("Saint Martin", f("MF"));
        put("Saint Pierre and Miquelon", f("PM"));
        put("Saint Vincent and the Grenadines", f("VC"));
        put("Samoa", f("WS"));
        put("San Marino", f("SM"));
        put("Sao Tome and Principe", f("ST"));
        put("Saudi Arabia", f("SA"));
        put("Senegal", f("SN"));
        put("Serbia", f("RS"));
        put("Seychelles", f("SC"));
        put("Sierra Leone", f("SL"));
        put("Singapore", f("SG"));
        put("Sint Maarten", f("SX"));
        put("Slovakia", f("SK"));
        put("Slovenia", f("SI"));
        put("Solomon Islands", f("SB"));
        put("Somalia", f("SO"));
        put("South Africa", f("ZA"));
        put("South Korea", f("KR"));
        put("South Sudan", f("SS"));
        put("Spain", f("ES"));
        put("Sri Lanka", f("LK"));
        put("Sudan", f("SD"));
        put("Suriname", f("SR"));
        put("Svalbard and Jan Mayen", f("SJ"));
        put("Swaziland", f("SZ"));
        put("Sweden", f("SE"));
        put("Switzerland", f("CH"));
        put("Syria", f("SY"));
        put("Taiwan", f("TW"));
        put("Tajikistan", f("TJ"));
        put("Tanzania", f("TZ"));
        put("Thailand", f("TH"));
        put("Togo", f("TG"));
        put("Tokelau", f("TK"));
        put("Tonga", f("TO"));
        put("Trinidad and Tobago", f("TT"));
        put("Tunisia", f("TN"));
        put("Turkey", f("TR"));
        put("Turkmenistan", f("TM"));
        put("Turks and Caicos Islands", f("TC"));
        put("Tuvalu", f("TV"));
        put("U.S. Virgin Islands", f("VI"));
        put("Uganda", f("UG"));
        put("Ukraine", f("UA"));
        put("United Arab Emirates", f("AE"));
        put("United Kingdom", f("GB"));
        put("United States", f("US"));
        put("Uruguay", f("UY"));
        put("Uzbekistan", f("UZ"));
        put("Vanuatu", f("VU"));
        put("Vatican", f("VA"));
        put("Venezuela", f("VE"));
        put("Vietnam", f("VN"));
        put("Wallis and Futuna", f("WF"));
        put("Western Sahara", f("EH"));
        put("Yemen", f("YE"));
        put("Zambia", f("ZM"));
        put("Zimbabwe", f("ZW"));
    }};

    private static String f(String token) {
        return String.format("https://www.countryflags.io/%s/flat/32.png", token);
    }

    public static String get(String country) {
        return MAP.getOrDefault(country, "https://img.icons8.com/ios/26/000000/vertical-flag.png");
    }
}
